#
# Globale Facts setzen
#
- hosts: localhost
  gather_facts: true
  tasks:
    - name: include global mode
      ansible.builtin.include_tasks:
        file: "global_setup.yml"

#
# Multipass Instanzen erzeugen
# 
- hosts: localhost
  gather_facts: false
  roles:
    - role: multipass_create_vm